### ISSUE TITLE
Exception debugging script with assign function

### ISSUE THREAD

**Issue by ktisha** [sproshev/TheRPlugin#16]
file text:
```assign("x$a",1)
z <- 1
```

java.io.IOException: Actual response type is not the same as expected: [actual: EMPTY, expected: RESPONSE]
	at com.jetbrains.ther.debugger.interpreter.TheRProcess.execute(TheRProcess.java:23)
	at com.jetbrains.ther.debugger.utils.TheRDebuggerUtils.loadVar(TheRDebuggerUtils.java:125)
	at com.jetbrains.ther.debugger.utils.TheRDebuggerUtils.loadVars(TheRDebuggerUtils.java:31)
	at com.jetbrains.ther.debugger.utils.TheRDebuggerUtils.loadUnmodifiableVars(TheRDebuggerUtils.java:45)
	at com.jetbrains.ther.debugger.TheRMainFunctionDebugger.advance(TheRMainFunctionDebugger.java:113)
	at com.jetbrains.ther.debugger.TheRDebugger.advance(TheRDebugger.java:84)
	at com.jetbrains.ther.xdebugger.TheRXDebugProcess.advance(TheRXDebugProcess.java:185)
	at com.jetbrains.ther.xdebugger.TheRXDebugProcess.resume(TheRXDebugProcess.java:145)
	at com.jetbrains.ther.xdebugger.TheRXDebugProcess.sessionInitialized(TheRXDebugProcess.java:83)
	at com.intellij.xdebugger.impl.XDebugSessionImpl.initSessionTab(XDebugSessionImpl.java:334)
	at com.intellij.xdebugger.impl.XDebugSessionImpl.init(XDebugSessionImpl.java:284)
	at com.intellij.xdebugger.impl.XDebuggerManagerImpl.startSession(XDebuggerManagerImpl.java:231)
	at com.intellij.xdebugger.impl.XDebuggerManagerImpl.startSession(XDebuggerManagerImpl.java:173)
	at com.jetbrains.ther.xdebugger.TheRDebugRunner.doExecute(TheRDebugRunner.java:53)
	at com.intellij.execution.runners.GenericProgramRunner$1.execute(GenericProgramRunner.java:43)

**Comment by sproshev** [comment]
Can't reproduce :( My revision is 9dfd5c29a2c6fdcfea363b4bf66d70fe02ff13e3.
