### ISSUE TITLE
Put breakpoint on for statement and hit "Step into"

### ISSUE THREAD

**Issue by ktisha** [sproshev/TheRPlugin#39]
Actual type is not the same as expected: [actual: EMPTY, expected: RESPONSE]
com.jetbrains.ther.debugger.exception.TheRUnexpectedExecutionResultException: Actual type is not the same as expected: [actual: EMPTY, expected: RESPONSE]
	at com.jetbrains.ther.debugger.executor.TheRExecutorUtils.execute(TheRExecutorUtils.java:20)
	at com.jetbrains.ther.debugger.executor.TheRExecutorUtils.execute(TheRExecutorUtils.java:32)
	at com.jetbrains.ther.debugger.function.TheRTraceAndDebugUtils.traceAndDebugFunctions(TheRTraceAndDebugUtils.java:25)
	at com.jetbrains.ther.debugger.function.TheRMainFunctionDebugger.advance(TheRMainFunctionDebugger.java:105)
	at com.jetbrains.ther.debugger.TheRDebugger.advance(TheRDebugger.java:110)
	at com.jetbrains.ther.xdebugger.TheRXDebugProcess.advance(TheRXDebugProcess.java:228)
	at com.jetbrains.ther.xdebugger.TheRXDebugProcess.access$100(TheRXDebugProcess.java:31)
	at com.jetbrains.ther.xdebugger.TheRXDebugProcess$4.run(TheRXDebugProcess.java:183)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by sproshev** [comment]
Can't reproduce, revision is cc048dbd86857a973949dcce5c7da8847d842de7.

I'm running the code below
```
packageNames <- .packages(all = TRUE)

for (name in packageNames) {
    shouldLoadLibrary = FALSE
}
```
with breakpoint on `for (name in packageNames) {`.

When breakpoint is reached I click F7 and there is no exception in the log.
